/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cookbook;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

import cookbook.backend.DatabaseMng;
import cookbook.backend.be_objects.LogIn;
import cookbook.backend.be_objects.Recipe;
import cookbook.backend.be_objects.User;
import cookbook.backend.be_controllers.UserController;
import cookbook.backend.be_controllers.FavoritesController;

class AppTest {
    // Commented out Greeting Test Case
    /*@Test void appHasAGreeting() {
         App classUnderTest = new App();
         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
     }*/
     private LogIn login;
     private DatabaseMng dbManager;
     private UserController userController;
     private FavoritesController favoritesController;

    @BeforeEach
    void setup() {
        dbManager = new DatabaseMng();
        userController = new UserController(dbManager);
        login = new LogIn(dbManager);
        favoritesController = new FavoritesController(dbManager);

    }

     @Test
     void testPasswordHashing() {
         String testPassword = "password123";
         String hashedPassword = login.hashPassword(testPassword);
 
         // Testa att hash-värdet inte är null och inte lika med klartextlösenordet
         assertNotNull(hashedPassword, "Hashed password should not be null");
         assertNotEquals(testPassword, hashedPassword, "Hashed password should not match plain text");
     }

    @Test
    void testUserSaveToDatabase() {
        User testUser = new User("user", "test user", "user", false, dbManager, null);
        userController.setUser(testUser);
        boolean isSaved = userController.saveToDatabase();

        assertTrue(isSaved, "User should be successfully saved to the database");
    }

    @Test
    public void test_addFavorite_validIDs() {
        // Arrange
        String userId = "1";
        Recipe recipe = new Recipe("1", "Ingredients", "RecipeName", "RecipeName");
    
        // Act
        boolean result = addFavorite(userId, recipe);
    
        // Assert
        assertTrue(result);
    }

}